#!/bin/bash

#alias
declare -A aliasArr
aliasArr[CONTAINER_NAME]="alias1,alias2"

# clear existing *.docker.local entries from /etc/hosts
sudo sed -i '/\.docker\.local$/d' /etc/hosts

# iterate over each machine
docker ps -a --format "{{.Names}}" \
| while read -r MACHINE; do

	MACHINE_IP="$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${MACHINE} 2>/dev/null)"
	
	if [[ ${aliasArr[$MACHINE]} ]]
	then
	    DOMAIN_NAME=$(echo ${aliasArr[$MACHINE]} | tr "," "\n")
    else
	    DOMAIN_NAME=( ${MACHINE} )
	fi

    for addr in $DOMAIN_NAME
    do
	    echo "add ${MACHINE_IP}	${addr}.docker.local"
	    [[ -n $MACHINE_IP ]] && sudo /bin/bash -c "echo \"${MACHINE_IP}	${addr}.docker.local\" >> /etc/hosts"
	    export no_proxy=$no_proxy,$MACHINE_IP
    done
        
done
